Contributions scoreboard
Yiffer-xyz/yiffer.xyz-contributions pull request #24
Opened 2022-10-09 16:03 UTC by toastythetoaster

2022-10-10 10:36 UTC, ragnarob requested changes
A couple of changes requested, and a few things that don't need changing but that we should replace with new UI components later

2022-10-10 10:36 UTC, ragnarob commented on app/routes/contribute/scoreboard/index.tsx
> +        <div className="flex mb-6">
Let's make this into a component! Will add as a task for later

2022-10-10 10:36 UTC, ragnarob commented on app/routes/contribute/scoreboard/index.tsx
> +            <Button
We should make an IconButton component as well. Will also add a task in the board.

2022-10-10 10:36 UTC, ragnarob commented on .prettierrc.js
> +  printWidth: 90,
Did we not talk about this? 😛

2022-10-17 18:05 UTC, ErikMelton approved these changes
LGTM, just need to fix the git history 😄

2022-10-22 19:11 UTC, toastythetoaster commented
> LGTM, just need to fix the git history 😄

this branch is going to end up killing me

2022-10-22 20:06 UTC, merged